name: Test

permissions:
  contents: write

on: [push]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  rust-test:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: install easy-install
        uses: ahaoboy/easy-setup@v1
        with:
          url: |-
            https://github.com/ahaoboy/wiztree-metafile
            https://github.com/pnpm/pnpm
      - name: build
        run: |
          pnpm install
          pnpm run build
      - name: wiztree-metafile
        run: |
          wiztree-metafile . > wiztree-metafile-${{ matrix.os }}.json
          node cli/cli.js -m dark wiztree-metafile-${{ matrix.os }}.json wiztree-metafile-${{ matrix.os }}.dark.png
          node cli/cli.js -m dark wiztree-metafile-${{ matrix.os }}.json wiztree-metafile-${{ matrix.os }}.dark.webp
          node cli/cli.js -m light wiztree-metafile-${{ matrix.os }}.json wiztree-metafile-${{ matrix.os }}.light.png
          node cli/cli.js -m light wiztree-metafile-${{ matrix.os }}.json wiztree-metafile-${{ matrix.os }}.light.webp
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: wiztree-metafile-${{ matrix.os }}
          path: |
            wiztree-metafile*
